name: common_ui
description: A new Flutter package project.
version: 0.0.3
homepage: null
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^3.0.2
  separated_list:
    git:
      url: https://github.com/xbrny/bitbani_packages.git
      path: packages/separated_list

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
