name: common_ui
description: A new Flutter package project.
version: 0.0.5
homepage: null
publish_to: none

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
